modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPL-v3"

[[mods]]
modId = "enchantedpotato"
version = "${version}"
displayName = "EnchantedPotato"
authors = "TeamPotato"
description = '''
A Minecraft mod.
'''